language: node_js

sudo: true

services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm install

after_success:
  - npm run coverage
  - npm run report-coverage

